# Generated by Django 5.0.6 on 2024-07-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
